### ISSUE TITLE
Hintergrund einiger Grafiken transparent machen

### ISSUE THREAD

**Issue by Huxinator** [st-universe/assets#10]
Hat sicher nicht die top Priorität. Aber es gibt viele Icons die einen schwarzen Hintergrund haben. Diese Icons werden hin und wieder auf einen farbigen Hintergrund (dem Seitenaufbau entsprechend) draufgeklatscht. Es würd sicherlich besser aussehen, wenn die Icons einen transparenten Hintergrund hätten.

**Comment by Bielhelm** [comment]
Das sollte zumindest bei den Buildings usus werden finde ich. Bei dem Fields wäre es eher kontraproduktiv, da wir schon festgestellt haben, daß mehrere "Schichten" übereinander gelegt, die Feld-Bonusse ausmachen.

**Comment by Huxinator** [comment]
Das war prinzipiell auf solche kleinen Icons bezogen. Also kleine Symbole usw die entweder einen Rahmen haben und nach dem Rahmen von außen immer noch schwarz sind, oder die die keinen Rahmen haben und einfach so einen schwarzen Hintergrund haben.

**Comment by Bielhelm** [comment]
Es werden soweit bekannt als Grundsatz inzwischen alle neuerstellten png32 bit files, soweit möglich transparent erstellt, bei gif-files geht das wohl nicht. Eventuell bitte Issue Closen?
