### ISSUE TITLE
Schiffsbilder

### ISSUE THREAD

**Issue by ghost** [st-universe/assets#106]
Nach ausführlicher Rücksprache. Es ist wohl absichtlich so vorgesehen, daß bestimmte Schiffstypen für einige Rassen NICHT gebaut werden sollten, Möglicherweise um mehr Reibung ins Spiel zu bringen.
Eine 100 % Zuordnung nach einem sinnvollen Schema bezüglich der Schiffstypen / Nummern konnte durch den bisherigen Designer leider nicht gewährleistet werden. Daher werden wir uns stur nach der Liste von @huxinator vorarbeiten.

- /stu3-assets/ships/gif
- /stu3-assets/ships/png -> in 32bit transparent
- entsprechende "stu_rumps.xls" geht jeweils @Huxinator

Eine aktuelle Arbeitsdatei wird in "stu_rumps2_datum.xls" über office 07 wird
intern laufend upgedated.. Ansonsten reicht Anfrage für aktuellen Stand,
der nur intern an die Kollegen im Team weitergegeben wird.

**Comment by Bielhelm** [comment]
Schiffsbilder laut vorliegender Excel-Liste von 904-2305 und Benennung fertig, Dist upgedated. Es sind in der Excelliste bzw. in Abgleich mit STU3.sql folgende Fehler aufgefallen:

1203 K´Pak klingonisch fehlt als Bild. In der letzten sql ist er aber drin
1403 K´Toch klingonisch zeigt einen Frachter an, ist aber ein "Jäger / Forschungsschiff"
1493 -> eigentlich klingonisch (?), noch kein Eintrag in Online Excel durchgeführt. Kein Bild erstellt 
2203 -> lt sql "unnamed KliFri Pls", kein Bild
2303 -> lt sql "unnamed KliFri Pls", kein Bild

**Comment by Bielhelm** [comment]
Weitere Schiffsbilder für Romulaner und Klingonen und die Überarbeitung lassen zur Zeit auf sich warten, da zunächst das Projekt : Forschungsbilder wichtiger ist.
