### ISSUE TITLE
Crew-Bilder fehlen

### ISSUE THREAD

**Issue by Huxinator** [st-universe/assets#22]
Für die Romulaner, Klingonen, Ferengi, Cardassianer fehlen noch die ganzen Crew-Icons. Auch kann man die Föderationsicons einwenig erweitern.

Bei den einzelnen Fraktionen kann man natürlich überlegen, welche Rassen noch so alles mit dabei wären. Remaner bspw. bei den Romulanern. Gorn oder Nausicaaner kann man bspw. den Klingonen unterordnen usw.

**Comment by usox** [comment]
Ja, definitiv mehr Rassen mitsamt entsprechender Bilder

**Comment by Bielhelm** [comment]
Ich würde folgende Liste als Hilfsmittel benutzen: (https://sto-de.gamepedia.com/Rasse)
Aus diversen Star Trek Büchern über Cardassianer, Ferengi und Romulaner, auch i.V. mit Star Trek Typhon Pact usw. werden sicher noch mehr hinzukommen können, falls gewünscht

**Comment by usox** [comment]
Sinnvoll. Man braucht jedoch auch einen Wahrscheinlichkeitswert für das Erzeugen der Rassen - gerade bei der Föderation. Menschen sind da sicherlich häufiger vertreten als z.B. Bajoraner.
