### ISSUE TITLE
Forschungsbilder

### ISSUE THREAD

**Issue by usox** [st-universe/assets#25]
Jede Forschung sollte, neben einer netten Beschreibung, auch ein schönes Bild haben.
Bei vielen Forschungen reicht als Bild vermutlich das, was sie freischaltet, und ein Rahmen drum rum. Z.b. Forschungen für Schiffsklassen haben ein Bild, in das die jeweilige Schiffsklasse eingebettet ist, Gebäude ebenso. Den Rest müsste man sich halt überlegen.

Wichtig ist: Dimensionen und Datei-Endung müssen einheitlich sein, die Bilder müssen nach der Forschungs-ID benannt in einem entsprechenden Ordner liegen. Was die Dimensionen angeht, bin ich noch nicht festgelegt. 90x90 oder 100x100 wären mal einen Versuch wert.

**Comment by Huxinator** [comment]
Schwierig einheitliche Bilder zu bekommen. Schiffe haben meist die unterschiedlichsten ausmaße. Die hoch zu skalieren kann ekelhaft werden. Genauso auch bei Gebäude.

**Comment by Bielhelm** [comment]
Nach Abschluss der Arbeit am Thema Fields (vorerst) 

Ein Brainstorming zum Thema Forschungsgrafiken kann frühestens 05.10 bei mir erfolgen. 
Ich schlage vor :Bis dahin sammeln wir einfach Ideen. 

- ggf dann Discord (Sprachchat mgl?) 
- werden diese Bilder fest eingebettet in den bisherigen Forschungsschirm (bleibt der so) ?
- sollen wir gleich nen Rahmen je Rasse mitmachen oder rein um die Bilder kuemmern?

**Comment by LWU86** [comment]
Wenn die Bilder echt 90x90 groß werden sollten, wäre dann nicht die Forschungsansicht etwas verzerrt? Die jetzigen Icons sind 24x22 und damit passgenau mit dem Namen bzw. dem Schriftzug.  Nen 90x90 dahinter würde doch auch diese Spalten entsprechend größer machen, oder?

**Comment by Bielhelm** [comment]
Ich bin mir sicher, daß sich Wolv in dem Issue klar darüber war, dass sich die Ansicht verschiebt und kann das mit berücksichtigen, Nächste Woche werden sich die drei vorläufigen Mitarbeiter für Bildgestaltung zusammensitzen und beraten. Bis dahin wäre es schön, die endgültig angepeilte Größe zu erfahren. Ich gebe aus meiner Erfahrung aber zu bedenken:

* Fields (40x40) Da wurden viele Einzelheiten nachgebessert und es hat lange gedauert, bis eines akzeptabel war. Es ist allgemein mit sehr viel mehr Aufwand verbunden, kleine Bilder zu machen, als größere, weil viele Einzelheiten herausretuschiert werden müssen.

* bisherige System und Forschungsbilder (24x22): Es grenzt an ein Wunder, daß überhaupt noch so viele Einzelheiten erkennbar waren, es war also nicht einmal quadratisch . Das erinnert an Atari 2600 Grafiken mit 16 Farben. 256 Farben sind auch schwer auf die Größe darstellbar von weitem.

* neue angepeilte Größe für Forschungsbilder (100x100) = Avatargröße: Prototypen für Rahmen von drei Rassen á  5 px / Seite breit mit 90x90 Bildern. Darauf könnte man auch noch etwas erkennen, wenn man Bilder verkleinert.

Bei einem Spiel, daß vorerst NICHT auf dem Handy nicht laufen wird, sitzen die meisten Leute heute vor Octacore Rechner mit 30 Zoll Bildschirmen, die mindestens 1920x1080 Bildpunkte anzeigen und 100x100 wären da schon zu groß? Oder 150x150 px für Allianzbilder? Wirklich?

**Comment by usox** [comment]
Mit der Bildgroesse der Forschungsbilder koennen wir uns noch nicht 100%ig festlegen festlegen, da es noch nicht klar ist, wie die Forschungsseite und Detailansicht aussehen wird. Sofern die Maße aber quadratisch sind, haben wir etwas mehr Flexibilitaet (z.b., wenn wir das Bild mal in gross, mal in klein brauchen).
Ich wuerde jetzt auch gedanklich nicht mal von `dem User am Octacore`-PC ausgehen sondern davon, dass das Spiel zu einem Punkt X auf allen Devices nutzbar ist - daher muss man auch das in Betracht ziehen (Und Nein, wir werden keine Fullscreen-Allianzbanner erlauben).

**Comment by Bielhelm** [comment]
Sollte mit dem Auftrag etwas anderes beabsichtigt gewesen sein, so bitte ich um Nachsicht, ich habe es so verstanden, daß zunächst, der im Spiel entgültig gültige "Rahmen" für die Forschung erstellt wird, in das die Bilder dann eingepasst werden, je nach Rasse.

Bis jetzt wurden 8 unterschiedliche "Rahmen" in 100x100, Bildgröße 90x90 für alle 3 Rassen und 1 jeweils grauen "Standart" Rahmen zur Auswahl erstellt. (mit Testbild - Mondkolonie, dass mit 90x90 hier noch gut erkennbar ist). 7 Rahmen wurden selbst erstellt, eines wurde zusammengestellt aus ehemaligen ST Games, 1 davon ist eines der bereits bekannte Prototyp.

**Comment by Bielhelm** [comment]
Die Maße bei den Forschungsbildern von 100x100 (also 10x10 ausser für die "Rasse") und 90x90 als Bild scheint sich bewährt zu haben und wird fortgeführt.

**Comment by Bielhelm** [comment]
Update :sämtliche Tier 1 Items haben Bilder. Es werden zusätzlich Icons für die Bilder entwickelt werden, die entsprechende "Upgrade" auf bestehende Forschungsprojekte haben. Bis jetzt dürften geschätzt gut 1 / 3 aller Bilder fertig sein.

**Comment by Bielhelm** [comment]
Update von "ghost". Sämtliche Forschungsbilder der Klassen 1.2.3.G.U aller 5 Rassen sind fertig. Einige Nachzügler sind dabei. Wäre zwar toll nur Trek oder SciFi Bilder zu nutzen, aber dazu braucht die Grafikabteilung Hilfe von außen. Von Nerds, die sich bereiterklaeren, Bilder aus Video Serien, die sie anschauen weiterzugeben. 100x100 mit teilweise verschobenen Rassen Rahmen hat sich m. E. bewährt.
