### ISSUE TITLE
Ich kann mich nicht bei euch im Forum Registrieren. Und auch nicht  im Spiel.

### ISSUE THREAD

**Issue by wumix** [st-universe/assets#262]
```
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
```
Für das Spiel Brauche ich einen Einladungscode.

**Comment by Huxinator** [comment]
Hallo Florian,
Im Forum sollte sich eigentlich jeder registrieren können. Dort kann man sich dann auch in einem entsprechenden Bereich vorstellen, um nach einem Einladungscode zu fragen. Alternativ kannst du auf unserer Seite auch auf den Chatbutton klicken. Der führt dann zu unserem Discord Server. Dort könntest du auch nachfragen. Möglicherweise findet sich ein Spieler der noch freie Einladungscodes hat.

**Comment by Huxinator** [comment]
Nachtrag:
Jip habs gerade geprüft. DIe Forenregistrierung scheint defekt zu sein. Ich habs notiert und wir werden uns baldmöglichst darum kümmern. Bis dahin schlag ich vor aufm Discord-Server nachzufragen.

**Comment by wumix** [comment]
Okay kann mir jemand an meine Email einen einladungscode schicken?

Die email stehtbin meinem profil

**Comment by Huxinator** [comment]
Jeder Spieler kann 3 Einladungscodes erzeugen und vergeben. Wir wenigen Leute hier auf Github haben eher keine Einladungscodes mehr. Ich würd vorschlagen, dass du auf der Homepage auf den Discord-Chat gehst und einfach mal bei den Spielern nachfragst, ob jemand einen Einladungscode für dich hat :)
