### ISSUE TITLE
Welche Lizenz?

### ISSUE THREAD

**Issue by Zurret** [st-universe/assets#363]
Unter welcher Lizenz ist das hier veröffentlicht? ^^ 
Da keine LICENSE vorhanden ist fehlt diese Information natürlich und man weiß nicht wie man diese Assets hier verwenden darf.

**Comment by Huxinator** [comment]
Alles unter dem Projekt st-universe läuft als MIT Lizenz. Sehen dafür keinen Grund, weshalb nicht irgendwer auch Spaß an irgendwelchen Code Stücken, Grafiken oder sonst was haben kann.

Ich habs für dieses Repository nochmal explizit hinzugefügt.
