### ISSUE TITLE
Eigennamen

### ISSUE THREAD

**Issue by ghost** [st-universe/assets#48]
Ich finde es für problematisch, wenn viele der einzelnen Items in STU gleich heißen. Würden manche Felder gleich zutreffend benannt sein, würde es weniger Improvisationstalent erfordern, um entsprechende Punkte richtig zu werten und gleich auf Anhieb genauere Entwickelungsarbeit leisten zu können. Ich stelle fest, dass z. B die Umbenennung (von 701-705.gif "Berge" in "Bergkette, Wüstenberge, Schneeberge, Ödlandberge, Krater Berge") alleine schon Anhaltspunkte geben würde, was für Farbnouncen entsprechende Items haben und zu welcher Planetenklasse diese zugehörig sind. Bei 186 x "Gasplanet" wird es noch viel schwieriger nachzuarbeiten, wenn diese nicht irgendwo einem echten Schema entsprechen.

**Comment by usox** [comment]
Gerade was den Gasriesen angeht, hast Du absolut recht. Nur ist es faktisch so, dass wir schlichtweg nicht wissen, was das fuer Felder sind. Soweit ich das weiss/erkennen kann, ist der Gasriese gar nicht als generierbarer Planet vorhanden, daher kann man zumindest an der Stelle derzeit nichts machen

**Comment by Bielhelm** [comment]
Ich bitte darum, das Thema "Umbenennung" allgemein global zu sehen. Da es an vielen Stellen in der DB die Arbeit und Unterscheidbarkeit in Stufen und eindeutigere Erkennbarkeit fördern würde, insbesondere die Tatsache : was ist vom Aufbau das "nächste" item in der Reihe usw
