### ISSUE TITLE
Grafiken und Ablauf

### ISSUE THREAD

**Issue by ghost** [st-universe/assets#6]
Hallo,
wie mit Kollege "Huxinator" besprochen, werden sämtliche Bilder von stu 3.0 neu und mit transparentem Hintergrund entwickelt. ( Adobe Photoshop - CS2 ist frei - Matritze als .psd gespeichert, und ins .png Format 32bit umgewandelt)

**Uneinigkeit herrscht bei dem Thema, ob bereits erstellte Bilder in psd-format ausserhalb des Repo "stu3-assets" für andere Mitarbeiter abgelegt werden sollen oder können?** 

(Hauptsächlich wäre das zur Erhaltung des ungefähren Styles ingame je Rasse besser, falls später neue Bilder durch unterschiedliche Mitarbeiter hinzukommen ( und die Probleme mit github haben)

**Comment by usox** [comment]
Also grundsaetzlich kann man die Bilder immer irgendwo hin packen. Es macht jedoch Sinn, diese im repository zu halten oder mindesten zu pflegen, da man hier eine zentrale Stelle hat, an der alle Daten immer vorhanden und aktuell sind.

**Comment by Bielhelm** [comment]
Die Bilder unter /gfx/buildings" stehen in einer Struktur. Eine erste Tabelle wurde erstellt, aber es ist eine "Ordnernummer = entspricht Bild mit Namen" Tabelle wohl in Arbeit.
Die einzelnen bereits fertiggestellten Gebäude und Platzhalter sind viel zu "pixelig" als dass sie auf 40 x 40 px direkt als png entstanden sind. Daher sind diese wohl als svg Vektorgrafiken mit zusätzlichem Programm wesentlich größer  erstellt und dann transparent ins png umgewandelt worden?
Wie war die damalige Arbeitsweise, soweit das noch bekannt ist?

**Comment by usox** [comment]
Wie die Bilder `damals` erzeugt wurden, kann Dir nur einer sagen - und der bin nicht ich ;)

**Comment by Bielhelm** [comment]
Ja. Ich habs schon befürchtet.

**Comment by Bielhelm** [comment]
### **Es gibt Probleme mit mehreren Einzelheiten:** 

- PNG 32 bit ist wohl das Format nach Wahl für die Tiles ingame
- bei 40 x 40 px funktionieren m.E. Ankerpunkte bei svg Dateien nicht wirklich 
(wie bereits im anderen Threads beschrieben.)

- Das Aus / Zuschneiden von Bildern größerer (schon vorhandener) Real- Bilder und deren Verkleinerung wird für zügiges Arbeiten dringend nötig sein.

- Das Neuanlegen mit SVG durch geometrische Formen und deren Verkleinerung und darauffolgende nachträgliche Umwandlung, wird m.E. aufwändiger vonstatten gehen und ggf. zig Monate Aufwand verursachen.

### **Fragen:**

- Gibt es irgendwelche Vorgaben bezüglich der Ansichten (*) der Minibilder ingame oder sind wir darin frei - solange man sich auf einen Ansicht (von vorne, von vorne seitlich oder von oben einigen kann)?  

((*) Grund: Ein Kollege im Team meint, daß nur Ansichten von der Vogelperspektive, die minimal versetzt sind, wie in 2.5 - den Anforderungen des Teams entsprechen würden (?))

- Gibt es irgendwelche Dinge bei 40 x 40 px großen Bildern bezüglich der Rechtsfragen, Urheberrecht etc, zu beachten, oder sind diese einfach in die Felder einzupassen?

(Grund: Ein Kollege im Team meint, daß sämtliche Bilder vollständig authark, selbst und auch ohne die Zuhilfenahme von bereits vorhandenen STU 2.5er Bildern zu erstellen sind, was aber wesentlich mehr Zeit in Anspruch nehmen wird)

**Comment by Huxinator** [comment]
Also zumindes bei dem ersten "Ein Kollege im Team.." meinst du wohl mich ;)

Ich seh das so, dass die Kolonieansicht im allgemeinem aus der Vogelperspektive ist. So als wenn man aus den Orbit halt drauf schaut und nicht von der Seite. Wäre auch mMn komisch wenn man vom Schiff aus einen Planeten scant und man dann alles von einer Seite sieht.

Die Orbitalgebäude sind im Gegensatz dazu mMn von der Seite aus zu sehen. So wie es auch in den vorherigen Versionen immer war.

**Comment by Bielhelm** [comment]
Ich kann mich der Meinung von Huxinator nicht anschließen. Wir sollen die alte Sachen, so fern es geht, zunächst mal skalieren und die Beta mit drei Rassen und überhaupt irgendwelchen Bildern zum Laufen bringen. Von welcher Seite was gezeichnet und skaliert wird, dürfte erstmal egal sein, wir gewinnen sicher keinen Wettbewerb damit. 

Neue Grafiken brauchen viel mehr Zeit und Aufwand. Die Beta wurde schon vor x Jahren entwickelt und ist deshalb nicht fertig, weil auf zuviel "Genauigkeit" und "Schönheit" der Grafiken Wert gelegt wurde. Das hat das Projekt schon mal gestoppt. Ich sehe keinen Sinn es nochmal auf dieselbe Art zu versuchen. 

Wir haben jede Menge freie CC0-lizensierte Satellitenbilder und Stocks im Netz, um das zu versuchen,
Weitere urheberrechtliche Bedenken und Gegenprüfung würden uns weit zurückwerfen mit der Bildentwicklung.

**Comment by usox** [comment]
Ich denke, es macht schon Sinn, sich _vor_ der eigentlichen Arbeiten ein paar Dinge festzuhalten - da bin ich bei @Huxinator. Bildgröße und Perspektive sollte man da imho schon geklärt haben - v.a. bevor man alles dreimal machen muss.
Auf der anderen Seite sehe ich die Bilder - wie vieles andere - als iterativen Prozess. Es wird ein paar Durchgänge brauchen, bis man sich da gefunden hat und alles stimmig wird - so lange alle das gleiche Ziel vor Augen haben.

**Comment by usox** [comment]
Addendum: Bevor man jetzt irgendwelche Bilder nach Motto `Hauptsache was da` nimmt, sollte man mal lieber noch klären, was man eigentlich will.
Den Charme von STU haben zu einem guten Teil die Pixelgrafiken ausgemacht und ich bin der Ansicht, dass man diesen Stil beibehalten sollte. Ob man jetzt z.B. fuer die Oberflaechen-Tiles "gepixelte" Satelliten-Bilder nimmt wie in #2 angesprochen oder whatever  - das spielt keine Rolle, es muss einfach zum Rest passen.

Man kann hier doch erstmal - bevor man den grossen Wurf macht, einfach ein paar Beispiele bringen und zusammen besprechen. Verschiedene Groessen, verschiedene Perspektiven - am besten gleich 2-3 Bilder, damit man ein Gefühl bekommt. Und was das zeitliche angeht: Ich gehe nicht davon aus, dass das Spiel bis Jahresende in ein Stadium kommt, mit dem man eine richtige Beta ins Auge fassen kann - da fehlt es konzeptionell noch an einigen Ecken.

**Comment by Bielhelm** [comment]
Ich hab mich zurückgehalten mit Kommentar zu dem Issues, weil ich lieber erst was zeige und dann drüber reden möchte, aber einige Dinge MUSSTEN vorab einfach besprochen werden. Ich bin mit HUX jetzt etwa so verblieben : 

* Wir werden uns primär um die "Alten Bilder" kümmern, die ausschließlich im SQL-DUMP auftauchen
* es gibt einige Bilder die im Dump auftauchen, aber nicht in den "Fields" oder "Buildings" vorhanden sind. 
* Manche sind auch unzureichend beschrieben wenn 5 x in anderen Farben gefärbt "Berge" in der Liste stehen etc. (die sollte man beizeiten mal umbenennen)
* Es wird natürlich erstmal improvisiert werden.
* Ich persönlich werde freie Satellitenbilder und freies Bildmaterial benutzen, welches zusammengeschnitten wird. Dazu besteht bereits eine umfangreiche Quellenliste. (wie bereits hier beshrieben: [https://github.com/usox/stu3-assets/issues/2]
* Mehrere Perspektiven von allen Bildern dürften durch Spiegelung möglich sein, da mach ich mir auch noch keinen Kopf.
